
services:
  ###> PostgreSQL ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sy-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-sy-app}", "-U", "${POSTGRES_USER:-symfony}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  ###< PostgreSQL ###

  ###> pgAdmin ###
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - database
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  ###< pgAdmin ###

volumes:
  database_data:
  pgadmin_data:
